# Generated by Django 4.2.29 on 2026-03-12 19:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SarcasmAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text_content', models.TextField(blank=True)),
                ('has_image', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SarcasmResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sarcastic', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('reasoning', models.TextField(blank=True)),
                ('text_score', models.FloatField(default=0.0)),
                ('image_score', models.FloatField(default=0.0)),
                ('emoji_score', models.FloatField(default=0.0)),
                ('claude_score', models.FloatField(default=0.0)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analyzer.sarcasmanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='ImageInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images/')),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_input', to='analyzer.sarcasmanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='ModalityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('emoji', 'Emoji'), ('claude', 'Claude AI')], max_length=10)),
                ('score', models.FloatField()),
                ('confidence', models.FloatField(default=0.0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modality_results', to='analyzer.sarcasmanalysis')),
            ],
            options={
                'unique_together': {('analysis', 'modality')},
            },
        ),
    ]
